### ISSUE TITLE
Would it be easy to have FlipMode enable by default?

### ISSUE THREAD

**Issue by e-gaulue** [RaffaeleMorganti/pdf-viewer#1]
Good job. Simple and readable.

Anyway to arrive directly on a page with FlipMode enable (and button pressed).

Best regards,

**Comment by e-gaulue** [comment]
OK, it's written in known buggs. Does not seem strange because a lot of calculation is done depending on mode in pdf.js.

Any trick, like moving to to this mode after a while ?

Regards,

**Comment by e-gaulue** [comment]
Well,

I don't know if it can help, but I've set the viewer to load directly with zoom-mode set to 'fit-page' and spread-mode set to EVEN.

Then I added a small piece of script to change the scroll-mode once 'pagesload':
```
document.addEventListener('pagesloaded', function (e) {
	PDFViewerApplication.pdfViewer.scrollMode=3;
}, true);
```

And it looks to handle what I was looking for. Opening my pdf directly in flip mode. As long as I don't fall on any other troubles.

Regards,

**Comment by RaffaeleMorganti** [comment]
Thanks for your feedback. I'm going to test your solution and update the project

**Comment by RaffaeleMorganti** [comment]
With lastest release seems the problem is solved.
Default PDFjs behavior is to load files in UNKNOWN scroll mode.
To change this and load pdf directly in Book-flip mode simply edit the `getDefaultPreferences()` function in  **_pdfjs/viewer.js_** file.
In particular at line **_13'874_** changing from: `"scrollModeOnLoad": -1,`to `"scrollModeOnLoad": 3,`

**Comment by Numerizen** [comment]
That last comment made my day. Thanks a lot.
